Lets try this

diff --git a/.github/workflows/continuous-deployment.yml b/.github/workflows/continuous-deployment.yml
--- a/.github/workflows/continuous-deployment.yml
+++ b/.github/workflows/continuous-deployment.yml
@@ -32,12 +32,10 @@ jobs:
                   LATEST_PUBLISHED_VERSION=$(npm view $PACKAGE_NAME version)
                   echo "Latest published version is $LATEST_PUBLISHED_VERSION"
 
-                  if [ "$CURRENT_VERSION" = "$LATEST_PUBLISHED_VERSION" ] then
-                    echo "Version conflict detected! The version $CURRENT_VERSION is already published."
-                    echo "::set-output name=conflict::true"
-                  else
-                    echo "No version conflict. Proceeding with the workflow."
-                    echo "::set-output name=conflict::false"
+                  if [ "$CURRENT_VERSION" = "$LATEST_PUBLISHED_VERSION" ]; then
+                      echo "Current version is the same as the latest published version. Failing the run."
+                      exit 1
+                  fi
 
             - name: Get current date
               if: steps.version_check.outputs.conflict == 'true'
